### ISSUE TITLE
Consider submitting to asdf plugins repository

### ISSUE THREAD

**Issue by cmur2** [beardix/asdf-argocd#1]
Did you consider submitting an entry to https://github.com/asdf-vm/asdf-plugins for this plugin?
From the requirements it looks like this plugin already follows all best practices implementation and testing-wise :+1:

**Comment by essh** [comment]
Thanks for the reminder. I will look into doing this soon.

**Comment by essh** [comment]
This plugin is now included in the asdf plugin list.
